### ISSUE TITLE
Hundreds of electron process

### ISSUE THREAD

**Issue by asafyish** [FWeinb/electron-screenshot-service#12]
Hi,

After using and restarting many times, I see that we have hundreds of electron process, 
maybe it will help to use something like https://www.npmjs.com/package/child-killer to ensure process are dead when the parent process dies.

**Comment by FWeinb** [comment]
That sounds very strange. Is your application exited gracefully or crashing?

**Comment by asafyish** [comment]
We are using pm2 (https://github.com/Unitech/pm2) and doing pm2 restart. I am not exactly sure how it kill the process.

**Comment by FWeinb** [comment]
It looks like pm2 is [sending](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#cleaning-states-and-jobs-before-stop) a SIGINT to the process. So you might want to add the `screenshot.close()` call like this:

```js
process.on('SIGINT', function() {
  screenshot.close();
});
```

**Comment by asafyish** [comment]
Tried that... no luck. we still have hundreds of process.
BTW, we are using scale to 20. Is that related ?

**Comment by FWeinb** [comment]
Scale 20 should just scale the amount to 20 processes (so approx. 20 electron + 20 electron helpers)

**Comment by asafyish** [comment]
Maybe using something like https://npmjs.org/package/child-killer when spawning the process could help ?

**Comment by FWeinb** [comment]
This sounds really strange. Is the callback called by pm2? `child-killer` is polling every 100ms for each process, I would rather not do that.

**Comment by asafyish** [comment]
We are using Ubuntu 15.04.
What solved the problem is listening fro SIGTERM:

```js
process.on('SIGTERM', function () {
		screenshot.close();

		setTimeout(function() {
			process.exit(0);
		}, 1000)
	});
```

**Comment by FWeinb** [comment]
Glad you found a solution.
