### ISSUE TITLE
count is not updated when a spawned process crashes

### ISSUE THREAD

**Issue by asafyish** [FWeinb/electron-screenshot-service#15]
Hi,

When using electron-screenshot-service, sometimes the electron process crashes for unknown reasons, that's not a problem on it's own, but electron-screenshot-service doesn't decrease the count, so the next screenshot call fails.

Will you accept a PR for that ? it will move startElectron into createBrowser because it's needs acces to count.

**Comment by asafyish** [comment]
Also, it seems the commands are still sent to the dead process, and because it's dead - you never get a reply.

**Comment by FWeinb** [comment]
I would really like a PR for better process management. I don't have much time at hand currently.

**Comment by asafyish** [comment]
Attached #16

**Comment by FWeinb** [comment]
:+1:
