### ISSUE TITLE
Feature Request: Inject JavaScript

### ISSUE THREAD

**Issue by samcus** [FWeinb/electron-screenshot-service#17]
Similar to how we inject CSS. Possible? Also is there an easy way to select specific dom elements to capture? I could do a hide all and show only what I want but I'd like a better way to specify dom capture.

**Comment by FWeinb** [comment]
Electron doesn't provide a way to just capture a specific DOM element. Injecting JS sounds interesting.

**Comment by FWeinb** [comment]
Supported in `3.2.0` 🎆
