### ISSUE TITLE
Not Working on Heroku Deployment

### ISSUE THREAD

**Issue by samcus** [FWeinb/electron-screenshot-service#18]
My test is working on my local server (I'm running OSX,) but it is not working on my Heroku dyno (Linux)

I tried removing "." from "./" in my output
I also tried swapping "./" with __dirname

Neither worked, and I'm receiving an application error on my Heroku

**Comment by samcus** [comment]
Also, the error being returned is 503 with advance details of a timeout error (meaning it is taking longer than 30 seconds) I ran a performance capture on my local machine and it is generating all my files within 8 seconds so I'm not sure what is causing it to hang.

**Comment by samcus** [comment]
Wondering if it could be related to something like this https://github.com/stomita/heroku-screenshot/tree/master/phantomjs I know this isn't phantomjs, but it might point us in the right direction.

https://devcenter.heroku.com/articles/stack

**Comment by JacksonGariety** [comment]
@samcus Heroku doesn't have xvfb: https://en.wikipedia.org/wiki/Xvfb. If you can get it working, many will be happy. I have been unable.
