### ISSUE TITLE
`page` option not working

### ISSUE THREAD

**Issue by stefanjudis** [FWeinb/electron-screenshot-service#20]
Hey hey,

thanks for this. I'd really go for electron for screenshots.

Unfortunately this code here:

```
#!/usr/bin/env node

var fs         = require('fs');
var screenshot = require('electron-screenshot-service');

screenshot({
  url    : 'http://www.loopline-systems.com/en',
  width  : 1024,
  height : 2000,
  page   : true
})
.then( function( img ){
  fs.writeFileSync('./styleguide.png', img.data );

  screenshot.close();
} )
.catch( function( error ) {
  console.log( error );

  screenshot.close();

  process.exit( 1 );
} );
```

Does not generate the whole image. `page` seems to be completely ignored... Any comments on that? 

Installed electron-prebuilt version is

```
electron-prebuilt@1.2.0
```

Thanks in advance.

**Comment by FWeinb** [comment]
Determining the full size of an webpage isn't [that easy](https://github.com/FWeinb/electron-screenshot-app/blob/master/index.js#L100-L103). The page you try to take an screenshot off is having 'body,html{width:100%;height:100%}` on there css and have an `div` wrapping the whole content. I didn't find a way to do it more reliable.

**Comment by stefanjudis** [comment]
Seems to be fixed. Thanks. 🍻

**Comment by stefanjudis** [comment]
Hey hey,

thanks for the fix... I just came across a different problem... When taking pictures of a fairly long site the output is just a full transparent png...

![styleguide](https://cloud.githubusercontent.com/assets/962099/16191885/b0076010-36e6-11e6-8127-8fb9ab8bba5c.png)

Did you ever experience this? The command itself succeeds properly.

We'd like to use `electron-screenshot-service` for our styleguide which is fairly long.
