### ISSUE TITLE
Electron error popup if service is not closed immediately after screenshot

### ISSUE THREAD

**Issue by peerbolte** [FWeinb/electron-screenshot-service#24]
Whenever I take a screenshot and not run screenshot.close() afterwards, I will get the following electron error in a popup:

```
Uncaught Exception:
TypeError: Cannot read property 'id' of null
    at Timeout.makeScreenshot (<PATH>/node_modules/electron-screenshot-service/electron-service/node_modules/electron-screenshot-app/index.js:61:42)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```
Is this expected behaviour? If so the following might be a noob question but here we go:

Do I have to close the service after each screenshot (as this prevents the error from showing)? If so, how do I take another screenshot after closing the service?

screenshot.scale(5)
I'm on OSX 10.11
electron-screenshot-service: 3.1.3

**Comment by FWeinb** [comment]
Can you test this with `3.2.0` You should not have `.close()` it every time. This is definitely not expected behaviour.

**Comment by peerbolte** [comment]
Just tried it with 3.2.0, no luck :(. Still getting the errors

**Comment by FWeinb** [comment]
I just tested it with the `example/multiple.js` and everything is working fine. Can you provide a simple example that fails for you?

**Comment by peerbolte** [comment]
`example/multiple.js ` runs `screenshot.close()` after running it? What happens if you omit that?

**Comment by FWeinb** [comment]
It runs it after all screenshots where made. `Promise.all([])` waits till all the promises are fulfilled.

**Comment by peerbolte** [comment]
There are three iframes on the page I am trying to capture. When I visit a page without iframes, the error does not occur. Could this be the possible source for the problem?

**Comment by FWeinb** [comment]
Thanks for the hint. I will try with multiple iframe!

**Comment by FWeinb** [comment]
I can't reproduce it here. I tried with multiple screenshot of the front page of `codepen.io` where 6 iframes are loaded each time and everything is working fine.

**Comment by peerbolte** [comment]
did you omit screenshot.close() ? In my case I want to keep the process open, as I send multiple domains to process over time.

**Comment by FWeinb** [comment]
[Here](https://gist.github.com/FWeinb/684872b0957e9ecabfc84491ccc62a590) is the code I am using.

**Comment by peerbolte** [comment]
gives a 404

**Comment by FWeinb** [comment]
Sorry, should work now.

**Comment by peerbolte** [comment]
hi, this [code](https://gist.github.com/peerbolte/ac3ba92e11fe4d7321ab517fe1a53d6a) gives me the error. It's not consistent, you might need to run it a couple of times. 

It might have something to do with the load of the websites in the iframes? 
Or does this occur because screenshot.close() is never called?

**Comment by FWeinb** [comment]
When you run `cat node_modules/electron-prebuilt/dist/version` in the root of your project dose this print `v1.2.6`?

**Comment by peerbolte** [comment]
yes

**Comment by FWeinb** [comment]
This is a hard one... I can't reproduce it on my side.

**Comment by peerbolte** [comment]
Really appreciate the help. I understand it's tricky to debug this way. Another error I get (not always)

`Uncaught Exception:
TypeError: Cannot read property 'id' of null
    at Timeout.makeScreenshot (<PATH>/node_modules/electron-screenshot-service/electron-service/node_modules/electron-screenshot-app/index.js:61:42)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by FWeinb** [comment]
Just tried using `Network Link Conditioner` to throttle my connection to 3G but it still worked. There seams to be a race condition in the iframe detection code.

**Comment by peerbolte** [comment]
I'm still getting an error:
I really don't understand, shouldn't the return prohibit the code from executing?
```
Uncaught Exception:
TypeError: Cannot read property 'capturePage' of null
    at Timeout.setTimeout (<PATH>/node_modules/electron-screenshot-service/electron-service/node_modules/electron-screenshot-app/index.js:85:17)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by peerbolte** [comment]
Are the "return if popupWindow is not defined" solutions at line 60 and 81 valid enough to implement? As I think this solved the issue.

**Comment by FWeinb** [comment]
Added in electron-screenshot-app@3.1.1
