### ISSUE TITLE
PORT issue on windows

### ISSUE THREAD

**Issue by peerbolte** [FWeinb/electron-screenshot-service#27]
on windows, there is an issue when connecting to the sockets. 

```
Uncaught Exception:
Error: connect EADDRNOTAVAIL 0.0.0.0:7601
	at Object.exports._errnoException (util.js:949:11)
	at exports._exceptionWithHostPort (util.js:972:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

It seems like axon is using 0.0.0.0 as a default ip address, while this might not be wanted. 
I think it might be an elegant solution to create an environment variable for HOST:
[pull request](https://github.com/FWeinb/electron-screenshot-service/pull/26
)

when specifying `127.0.0.1` the issue goes away

**Comment by FWeinb** [comment]
Fixed by #26
