### ISSUE TITLE
using electron-prebuilt instead of implementing it

### ISSUE THREAD

**Issue by khejing** [FWeinb/electron-screenshot-service#3]
I see almost the same code in install.js as electron-prebuilt, so why not just use it? Add peer dependency of electron-prebuilt in pacakge.json will be OK.

**Comment by FWeinb** [comment]
Because I would like to specify the electron version in this repository.

**Comment by khejing** [comment]
OK, I got it. It seems that electon-prebuilt shoud provide the function to specify the version of electron. Thank you
