### ISSUE TITLE
Uncaught (in promise) TypeError: Bad argument(…)

### ISSUE THREAD

**Issue by jensfranke** [FWeinb/electron-screenshot-service#31]
I try to run the example code (https://github.com/FWeinb/electron-screenshot-service#usage) with node 6.5.0, Chromium 53.0.2785.113, Electron 1.4.1 and I got the following error: 

`internal/child_process.js:289 Uncaught (in promise) TypeError: Bad argument(…)ChildProcess.spawn @ internal/child_process.js:289exports.spawn @ child_process.js:392spawn @ index.js:17(anonymous function) @ browser.js:79_tickCallback @ internal/process/next_tick.js:103
internal/child_process.js:289 Uncaught (in promise) TypeError: Bad argument(…)ChildProcess.spawn @ internal/child_process.js:289exports.spawn @ child_process.js:392spawn @ index.js:17(anonymous function) @ browser.js:79_tickCallback @ internal/process/next_tick.js:103`

Any ideas? Thanks in advance

**Comment by FWeinb** [comment]
Are you trying to use this module from inside of electron? This service is meant to be run directly from node not from inside electron. To create screenshots from within electron please have a look at [electron-screenshot-app](https://github.com/FWeinb/electron-screenshot-app).

**Comment by jensfranke** [comment]
@FWeinb Thanks for the explanation.
