### ISSUE TITLE
ERROR:browser_main_loop.cc(231)] Gtk: cannot open display

### ISSUE THREAD

**Issue by srhyne** [FWeinb/electron-screenshot-service#5]
Hi @FWeinb, 

[Thanks for your guidance on nw.js vs Electron](https://twitter.com/SRhyne/status/634712386927128577)! Very helpful.

I know this is more of an electron thing but I cannot make sense of what [@zcbenz](https://github.com/zcbenz) is saying in this issue https://github.com/atom/electron/issues/2472 and I'm new to Chromium. Any guidance you could offer would be incredibily helpful. 

Thanks in advance!

**Comment by FWeinb** [comment]
As @zcbenz explained. It is not possible to run electron without a X session attached. If you trying to run this on a headless server, you can use xvfb to start a virtual frame buffer and let electron attach to that.  For how to get this to work have a look at the [.travis.yml](https://github.com/FWeinb/electron-screenshot-service/blob/master/.travis.yml#L7-L23)

**Comment by srhyne** [comment]
Thank you @FWeinb. I didn't understand what @zcbenz's explanation and I could not find many other references to this problem. Thank you very much.
