### ISSUE TITLE
Example hangs when running multiple screen shots

### ISSUE THREAD

**Issue by nealshail** [FWeinb/electron-screenshot-service#9]
I'm trying to use the multiple.js example file with multiple urls

i.e. i've modified the code to 
```javascript
Promise.all(['http://www.google.de/','http://www.google.no/', 'http://www.google.se/', 'http://www.google.co.uk/'].map(function (url) {
```

and run
```
node example/multiple.js
```

I'm getting intermittent results, 

sometimes I get all the pngs produced fine, sometimes it just hangs with no error message.
My network connection is fine.

Any ideas?

> OSX 10.11.2.
> node  v5.2.0

**Comment by FWeinb** [comment]
Fixed in 2.0.0
